version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:latest
    ports:
      - "5000:5000"
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
    container_name: ift6758-serving
    networks:
      - app-network

  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:latest
    ports:
      - "8501:8501"
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
    depends_on:
      - serving
    container_name: ift6758-streamlit
    networks:
      - app-network

networks:
  app-network:
    driver: bridge